export const ERRORES={
    "AUTENTICACION": 401,
    "ARGUMENTOS INVALIDOS": 400, 
    "ERROR INTERNO DEL SERVER": 500,
    "BAD REQUEST": 400,
    "AUTORIZACION": 403,
    "INDETERMINADO": 500,
    "NOT FOUND": 404
}